Drop old changesets patch maintenance system
squid-cache/ci pull request #23
Opened 2023-03-25 00:31 UTC by yadij

This way of managing patches has not been useful since
migration to github.
The directory and scripts have already been removed from
v6 and later series, so this logic will break if left.

2023-04-17 18:02 UTC, rousskov requested changes

2023-04-17 18:02 UTC, rousskov commented on release/mk-release-series.sh
>      chmod g+w $subd || nuclearFallout
I cannot attach this change request to the right line, but `changesets` are still mentioned on line 129 above. Should that `changesets` directory be removed from that loop? I am not sure, but perhaps the script is no longer populating that directory?

2023-05-16 03:28 UTC, yadij commented on release/mk-release-series.sh
>      chmod g+w $subd || nuclearFallout
thanks. removed

2023-05-16 13:19 UTC, rousskov approved these changes

2023-05-16 13:19 UTC, closed without merging

2023-05-16 13:20 UTC, rousskov commented
@yadij, please remove this merged PR branch from the official repository.